# Generated by Django 2.2 on 2020-08-11 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('field', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('achievement', models.TextField()),
                ('objective', models.TextField()),
                ('exp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft', models.TextField()),
                ('technical', models.TextField()),
                ('organizational', models.TextField()),
                ('computer', models.TextField()),
                ('language', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.user')),
            ],
        ),
    ]
