# Generated by Django 2.2 on 2020-08-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signtable',
            new_name='user',
        ),
    ]
