# Generated by Django 2.2 on 2020-08-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20200811_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
