# Generated by Django 2.2 on 2020-08-12 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_auto_20200812_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='employer',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='circular',
            fields=[
                ('circular_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('salary', models.CharField(max_length=30)),
                ('requirements', models.TextField()),
                ('date', models.CharField(max_length=30)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.employer')),
            ],
        ),
    ]
