# Generated by Django 2.2 on 2020-08-12 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_circular_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='e_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.employer'),
        ),
    ]
