# Generated by Django 2.2 on 2020-08-13 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_auto_20200812_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSC',
            fields=[
                ('ssc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sschool', models.TextField()),
                ('s_group', models.CharField(max_length=10)),
                ('s_GPA', models.CharField(max_length=4)),
                ('s_board', models.CharField(max_length=20)),
                ('s_year', models.CharField(max_length=4)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.user')),
            ],
        ),
        migrations.CreateModel(
            name='PSC',
            fields=[
                ('psc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pschool', models.TextField()),
                ('p_GPA', models.CharField(max_length=4)),
                ('p_board', models.CharField(max_length=20)),
                ('p_year', models.CharField(max_length=4)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.user')),
            ],
        ),
        migrations.CreateModel(
            name='PHD',
            fields=[
                ('phd_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uni', models.TextField()),
                ('field', models.TextField()),
                ('phd_year', models.CharField(max_length=4)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.user')),
            ],
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('m_university', models.TextField()),
                ('m_program', models.CharField(max_length=4)),
                ('m_CGPA', models.CharField(max_length=4)),
                ('m_year', models.CharField(max_length=4)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.user')),
            ],
        ),
        migrations.CreateModel(
            name='JSC',
            fields=[
                ('jsc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('jschool', models.TextField()),
                ('j_GPA', models.CharField(max_length=4)),
                ('j_board', models.CharField(max_length=20)),
                ('j_year', models.CharField(max_length=4)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.user')),
            ],
        ),
        migrations.CreateModel(
            name='HSC',
            fields=[
                ('hsc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('hschool', models.TextField()),
                ('h_group', models.CharField(max_length=10)),
                ('h_GPA', models.CharField(max_length=4)),
                ('h_board', models.CharField(max_length=20)),
                ('h_year', models.CharField(max_length=4)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.user')),
            ],
        ),
        migrations.CreateModel(
            name='Honours',
            fields=[
                ('ho_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ho_university', models.TextField()),
                ('ho_program', models.CharField(max_length=4)),
                ('ho_CGPA', models.CharField(max_length=4)),
                ('ho_year', models.CharField(max_length=4)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='root.user')),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ho_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.Honours')),
                ('hsc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.HSC')),
                ('jsc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.JSC')),
                ('m_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.Masters')),
                ('phd_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.PHD')),
                ('psc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.PSC')),
                ('ssc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.SSC')),
            ],
        ),
    ]
