# Generated by Django 2.2 on 2020-08-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_auto_20200813_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
